export const sectionsConfig = [
  {
    title: 'Начало работы',
    links: [
      {
        pageTitle: 'Регистрация',
        pageUrl: 'signup',
        items: [
          {
            title: 'Страница Регистрации',
            image: 'signup-1.png',
            width: 316,
            height: 126,
            description: '',
            link: 'signup',
          },
          {
            title: 'Возможные ошибки',
            image: 'signup-2.png',
            width: 316,
            height: 126,
            description: '',
            link: 'errors',
          },
        ],
      },
      {
        pageTitle: 'Регистрация по ссылке-приглашению',
        pageUrl: 'signup-invite',
        items: [
          {
            title: 'Страница Регистрации',
            image: 'signup-invite-1.png',
            width: 250,
            height: 100,
            description: '',
            link: 'signup-invite',
          },
          {
            title: 'Сообщества',
            image: 'signup-invite-2.png',
            width: 250,
            height: 100,
            description: '',
            link: 'community',
          },
          {
            title: 'Приглашение не действительно',
            image: 'signup-invite-3.png',
            width: 250,
            height: 100,
            description: '',
            link: 'errors',
          },
        ],
      },
      {
        pageTitle: 'Настройка профиля после регистрации',
        pageUrl: 'welcome',
        items: [
          {
            title: 'Профиль',
            image: 'welcome-1.png',
            width: 250,
            height: 100,
            description: '',
            link: 'profile',
          },
          {
            title: 'Создание сообщества',
            image: 'welcome-2.png',
            width: 250,
            height: 100,
            description: '',
            link: 'add-community',
          },
          {
            title: 'Присоединение к сообществу',
            image: 'welcome-3.png',
            width: 250,
            height: 100,
            description: '',
            link: 'community-invite',
          },
          {
            title: 'Окончание настройки профиля',
            image: 'welcome-4.png',
            width: 250,
            height: 100,
            description: '',
            link: 'final',
          },
        ],
      },
      {
        pageTitle: 'Имя пользователя',
        pageUrl: 'nickname',
        items: [
          {
            title: 'Что такое имя пользователя?',
            image: 'nickname-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'nickname',
          },
          {
            title: 'Как изменить имя пользователя?',
            image: 'change-nickname-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'change-nickname',
          },
        ],
      },
      {
        pageTitle: 'Отображаемое имя',
        pageUrl: 'username',
        items: [
          {
            title: 'Что такое отображаемое имя?',
            image: 'username-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'username',
          },
          {
            title: 'Как изменить отображаемое имя?',
            image: 'change-username-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'change-username',
          },
        ],
      },
    ],
    sectionName: 'work-beginning',
    icon: 'start-working.svg',
  },
  {
    title: 'Аккаунт',
    links: [
      {
        pageTitle: 'Настройка профиля пользователя',
        pageUrl: 'user-settings',
        items: [
          {
            title: 'Где найти настройки аккаунта пользователя?',
            image: 'user-settings-cover.png',
            width: 314,
            height: 84,
            description: '',
            link: 'user-settings',
          },
          {
            title: 'Личные данные',
            image: 'personal-data-cover.png',
            width: 270,
            height: 84,
            description: '',
            link: 'personal-data',
          },
          {
            title: 'Персонализация',
            image: 'personalization-cover.png',
            width: 280,
            height: 84,
            description: '',
            link: 'personalization',
          },
          {
            title: 'Безопасность',
            image: 'security-cover.png',
            width: 250,
            height: 84,
            description: '',
            link: 'security',
          },
          {
            title: 'Звук и видео',
            image: 'sound-video-cover.png',
            width: 240,
            height: 84,
            description: '',
            link: 'sound-video',
          },
        ],
      },
      {
        pageTitle: 'Редактирование аватара пользователя',
        pageUrl: 'profile-photo-settings',
        items: [
          {
            title: 'Как редактировать аватар пользователя?',
            image: 'profile-photo-settings-cover.png',
            width: 116,
            height: 116,
            description: '',
            link: 'profile-photo-settings',
          },
        ],
      },
      {
        pageTitle: 'Изменение адреса электронной почты',
        pageUrl: 'change-email',
        items: [
          {
            title: 'Как поменять почту, привязанную к аккаунту?',
            image: 'change-email-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'change-email',
          },
        ],
      },
      {
        pageTitle: 'Подтверждение адреса электронной почты',
        pageUrl: 'confirm-email',
        items: [
          {
            title: 'Как поменять почту, привязанную к аккаунту?',
            image: 'confirm-email-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'confirm-email',
          },
        ],
      },
      {
        pageTitle: 'Смена пароля',
        pageUrl: 'change-password',
        items: [
          {
            title: 'Как поменять пароль?',
            image: 'change-password-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'change-password',
          },
        ],
      },
      {
        pageTitle: 'Удаление аккаунта',
        pageUrl: 'delete-account',
        items: [
          {
            title: 'Как удалить аккаунт?',
            image: 'delete-account-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'delete-account',
          },
        ],
      },
    ],
    sectionName: 'account',
    icon: 'settings.svg',
  },
  {
    title: 'Сообщества',
    links: [
      {
        pageTitle: 'Создание сообщества',
        pageUrl: 'add-community',
        items: [
          {
            title: 'Как создать сообщество?',
            image: 'add-community-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'add-community',
          },
        ],
      },
      {
        pageTitle: 'Настройка сообщества',
        pageUrl: 'community-settings',
        items: [
          {
            title: 'Как настроить сообщество?',
            image: 'communities-settings-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'community-settings',
          },
          {
            title: 'Роли',
            image: 'communities-roles-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'roles',
          },
          {
            title: 'История активности',
            image: 'communities-activity-history-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'activity-history',
          },
          {
            title: 'Участники',
            image: 'community-members-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'members',
          },
          {
            title: 'Классы',
            image: 'communities-classes-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'classes',
          },
          {
            title: 'Удалить сообщество',
            image: 'delete-community-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'delete-community',
          },
        ],
      },
      {
        pageTitle: 'Категории',
        pageUrl: 'category',
        items: [
          {
            title: 'Как создать категорию?',
            image: 'add-category-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'add-category',
          },
          {
            title: 'Настройки',
            image: 'category-settings-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'category-settings',
          },
          {
            title: 'Классы',
            image: 'classes-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'classes',
          },
          {
            title: 'Участники',
            image: 'category-members-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'category-members',
          },
          {
            title: 'Как добавить каналы в категорию?',
            image: 'category-add-channel-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'category-add-channel',
          },
        ],
      },
      {
        pageTitle: 'Приглашения',
        pageUrl: 'invitation',
        items: [
          {
            title: 'Как создать ссылку-приглашение?',
            image: 'add-invitation-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'add-invitation',
          },
          {
            title: 'Как стать участником сообщества по ссылке-приглашению?',
            image: 'join-community-cover.png',
            width: 341,
            height: 150,
            description: '',
            link: 'join-community',
          },
        ],
      },
    ],
    sectionName: 'communities',
    icon: 'settings.svg',
  },
  {
    title: 'Задания и тесты',
    links: [
      {
        pageTitle: 'Создание теста',
        pageUrl: 'add-test',
        items: [
          {
            title: 'Как создать тест?',
            image: 'add-test.png',
            width: 288,
            height: 93,
            description: '',
            link: 'add-test',
          },
          {
            title: 'Выбор ответа на вопрос',
            image: 'questions.png',
            width: 288,
            height: 93,
            description: '',
            link: 'questions',
          },
          {
            title: 'Настройки',
            image: 'test-settings.png',
            width: 288,
            height: 93,
            description: '',
            link: 'settings',
          },
        ],
      },
      {
        pageTitle: 'Создание задания',
        pageUrl: 'add-task',
        items: [
          {
            title: 'Как создать задание?',
            image: 'add-task.png',
            width: 288,
            height: 93,
            description: '',
            link: 'add-task',
          },
          {
            title: 'Настройки',
            image: 'task-settings.png',
            width: 288,
            height: 93,
            description: '',
            link: 'settings',
          },
        ],
      },
      {
        pageTitle: 'Редактирование заданий и тестов',
        pageUrl: 'edit',
        items: [
          {
            title: 'Как редактировать задание/тест?',
            image: 'edit.png',
            width: 288,
            height: 93,
            description: '',
            link: 'edit',
          },
        ],
      },
      {
        pageTitle: 'Модель оценивания',
        pageUrl: 'evaluation-system',
        items: [
          {
            title: 'Что такое Модель оценивания?',
            image: 'evaluation-system.png',
            width: 288,
            height: 93,
            description: '',
            link: 'evaluation-system',
          },
          {
            title: 'Отметки',
            image: 'grades.png',
            width: 288,
            height: 93,
            description: '',
            link: 'grades',
          },
        ],
      },
    ],
    sectionName: 'tests-and-tasks',
    icon: 'tests.svg',
  },
  {
    title: 'Видеоконференции',
    links: [
      {
        pageTitle: 'О видеоконференциях',
        pageUrl: 'about',
        items: [
          {
            title: 'Что такое сервис видеоконференций?',
            image: 'about-cover.png',
            width: 316,
            height: 126,
            description: '',
            link: 'about',
          },
          {
            title: 'Основные функции сервиса видеоконференций',
            image: 'functionality-cover.png',
            width: 160,
            height: 53,
            description: '',
            link: 'functionality',
          },
        ],
      },
      {
        pageTitle: 'Присоединиться к видеоконференции',
        pageUrl: 'join-videoconference',
        items: [
          {
            title: 'Как присоединиться к видеоконференции?',
            image: 'join-videoconference-cover.png',
            width: 219,
            height: 53,
            description: '',
            link: 'join-videoconference',
          },
        ],
      },
    ],
    sectionName: 'videoconference',
    icon: 'video.svg',
  },
];
