name: Common Build Steps

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true

env:
  yarn_version: 1.22.19
  npm_version: 10.1.0
  turbo_version: 2.3.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup node
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Downgrade yarn
        run: npm install -g yarn@${{ env.yarn_version }}

      - name: Install npm@10.1.0
        run: npm install -g npm@${{ env.npm_version }}

      - name: Install turbo
        run: npm install -g turbo@${{ env.turbo_version }}

      - name: Turbo prune
        run: turbo prune --scope=${{ inputs.app_name }}

      - name: Install dependencies
        working-directory: ./out
        run: npm install

      - name: Build application
        working-directory: ./out
        run: npm run build --filter==${{ inputs.app_name }}

      - name: Upload build as an artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ inputs.app_name }}
          path: ./out/apps/${{ inputs.app_name }}/out
