name: On push

on:
  push:
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy to production
        required: false
        default: false
        type: boolean

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  build-deploy:
    needs: prepare
    if: needs.prepare.outputs.app_name_matrix != '[]'
    strategy:
      fail-fast: false
      matrix:
        app_name: ${{ fromJSON(needs.prepare.outputs.app_name_matrix) }}
    uses: ./.github/workflows/common.yml
    with:
      app_name: ${{ matrix.app_name }}
      deploy_environment: >-
        ${{
          contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)
          && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
          && 'xi-production'
          || (
            inputs.deploy
            && 'xi-production-manual'
            || ''
          )
        }}
    secrets: inherit
