name: On push

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  build-deploy:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        app_name: ${{ fromJSON(needs.prepare.outputs.app_name_matrix) }}
    uses: ./.github/workflows/common.yml
    with:
      app_name: ${{ matrix.app_name }}
      deploy: ${{ github.ref == github.event.repository.default_branch }}
    secrets: inherit
