name: Production

on:
  push:
    branches:
      - main
      - devops/setup-ci-cd
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  build:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        app_name: ${{ fromJSON(needs.prepare.outputs.app_name_matrix) }}
    uses: ./.github/workflows/common.yml
    with:
      app_name: ${{ matrix.app_name }}
    secrets: inherit
